exports.secret = "j34kl2yhsd9bf78sdahn12gsazarkweamdfklxc";
exports.url = "hubandrock.com";
// exports.url_cat = "mercatambulant.cat";
// exports.url_es = "mercadilloambulante.com";
exports.url_api = "api.hubandrock.com"
exports.url_cat = "hubandrock.com";
exports.url_es = "hubandrock.com";
exports.secretBank = "mxijBH6d/T5lWNtd4PfwCZGhanKjACRf";
exports.delimiter = "-3024J11-";
exports.environment = "development";
exports.elements_display = 12;
exports.elements_premium = 6;
exports.destination_images = "/Users/ferranmaso/hubandrock/cenobify-api";
exports.prefix_table = "_";
exports.port = 1521;
