-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 12:52:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cenobifyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cenobifyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cenobifyDB` DEFAULT CHARACTER SET utf8 ;
USE `cenobifyDB` ;

-- -----------------------------------------------------
-- Table `cenobifyDB`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(150) NULL,
  `last_connection` DATETIME NULL,
  `creation` DATETIME NULL DEFAULT NOW(),
  `role_idrole` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_role1_idx` (`role_idrole` ASC) ,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `cenobifyDB`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`user_info` (
  `user_iduser` INT NOT NULL,
  INDEX `fk_user_info_user_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_user_info_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `cenobifyDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`module` (
  `idmodule` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NULL,
  `user_iduser` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idmodule`),
  INDEX `fk_module_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_module_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `cenobifyDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`field_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`field_type` (
  `idfield_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `min` INT NULL,
  `max` INT NULL,
  `null` TINYINT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idfield_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`group` (
  `idgroup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `module_idmodule` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `type` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idgroup`),
  INDEX `fk_group_module1_idx` (`module_idmodule` ASC),
  CONSTRAINT `fk_group_module1`
    FOREIGN KEY (`module_idmodule`)
    REFERENCES `cenobifyDB`.`module` (`idmodule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `group`
  ADD COLUMN `icon` VARCHAR(50) DEFAULT NULL;

ALTER TABLE `group`
  ADD COLUMN `foreignGroup1` INT DEFAULT NULL,
  ADD FOREIGN KEY `fk_group_foreignGroup1`(`foreignGroup1`) REFERENCES `group` (`idgroup`) ON DELETE SET NULL ON UPDATE SET NULL;

ALTER TABLE `group`
  ADD COLUMN `foreignGroup2` INT DEFAULT NULL,
  ADD FOREIGN KEY `fk_group_foreignGroup2`(`foreignGroup2`) REFERENCES `group` (`idgroup`) ON DELETE SET NULL ON UPDATE SET NULL;



-- -----------------------------------------------------
-- Table `cenobifyDB`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`section` (
  `group_idgroup` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `idsection` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idsection`),
  CONSTRAINT `fk_section_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `cenobifyDB`.`group` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`field` (
  `idfield` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `field_type_idfield_type` INT NOT NULL,
  `group_idgroup` INT NOT NULL,
  `group_idgroup_foreign` INT NULL,
  `order` INT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `section_idsection` INT NULL,
  PRIMARY KEY (`idfield`),
  INDEX `fk_field_file_type1_idx` (`field_type_idfield_type` ASC) ,
  INDEX `fk_field_group1_idx` (`group_idgroup` ASC) ,
  INDEX `fk_field_field1_idx` (`field_idfield` ASC) ,
  INDEX `fk_field_section1_idx` (`section_idsection` ASC) ,
  CONSTRAINT `fk_field_file_type1`
    FOREIGN KEY (`field_type_idfield_type`)
    REFERENCES `cenobifyDB`.`field_type` (`idfield_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `cenobifyDB`.`group` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_group_foreign1`
    FOREIGN KEY (`group_idgroup_foreign`)
    REFERENCES `cenobifyDB`.`group` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_section1`
    FOREIGN KEY (`section_idsection`)
    REFERENCES `cenobifyDB`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`permission` (
  `idpermission` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `group_idgroup` INT NOT NULL,
  PRIMARY KEY (`idpermission`),
  INDEX `fk_permission_user1_idx` (`user_iduser` ASC) ,
  INDEX `fk_permission_group1_idx` (`group_idgroup` ASC) ,
  CONSTRAINT `fk_permission_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `cenobifyDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `cenobifyDB`.`group` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`token` (
  `user_iduser` INT NOT NULL,
  `value` VARCHAR(100) NULL,
  INDEX `fk_token_user1_idx` (`user_iduser` ASC) ,
  PRIMARY KEY (`user_iduser`),
  CONSTRAINT `fk_token_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `cenobifyDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cenobifyDB`.`option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cenobifyDB`.`option` (
  `idoption` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `field_idfield` INT NOT NULL,
  PRIMARY KEY (`idoption`),
  INDEX `fk_option_field1_idx` (`field_idfield` ASC) ,
  CONSTRAINT `fk_option_field1`
    FOREIGN KEY (`field_idfield`)
    REFERENCES `cenobifyDB`.`field` (`idfield`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cenobifyDB`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `cenobifyDB`;
INSERT INTO `cenobifyDB`.`role` (`idrole`, `desc`) VALUES (1, 'admin');
INSERT INTO `cenobifyDB`.`role` (`idrole`, `desc`) VALUES (2, 'admin_group');
INSERT INTO `cenobifyDB`.`role` (`idrole`, `desc`) VALUES (3, 'user');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cenobifyDB`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `cenobifyDB`;
INSERT INTO `cenobifyDB`.`user` (`iduser`, `email`, `password`, `last_connection`, `creation`, `role_idrole`, `active`) VALUES (1, 'fm@ferranmaso.com', '$2a$05$sNdXgAF9JVRW3B6ofwfmputnmLi2m5N/8Uror7bEOKn82w5hUkcgm\n$2a$05$sNdXgAF9JVRW3B6ofwfmputnmLi2m5N/8Uror7bEOKn82w5hUkcgm', NULL, NULL, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cenobifyDB`.`field_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `cenobifyDB`;
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (1, 'normal text', 0, 100, 1, 'text');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (2, 'long text', 0, 200, 1, 'text');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (3, 'decimal 2 digits', 0, 10, 1, 'decimal');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (4, 'number', 0, 10, 1, 'number');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (5, 'checklist true false', 0, 0, 1, 'checklist');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (6, 'input', 0, 0, 1, 'input');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (7, 'checklist', 0, 0, 1, 'checklist');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (8, 'email', 0, 50, 1, 'email');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (9, 'dni/cif', 0, 10, 1, 'dni');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (10, 'phone', 0, 13, 1, 'phone');
INSERT INTO `cenobifyDB`.`field_type` (`idfield_type`, `name`, `min`, `max`, `null`, `type`) VALUES (11, 'select', 0, 0, 1, 'select');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cenobifyDB`.`token`
-- -----------------------------------------------------
START TRANSACTION;
USE `cenobifyDB`;
INSERT INTO `cenobifyDB`.`token` (`user_iduser`, `value`) VALUES (1, 'LFaHFh1P0K13pIg1uKqKXC7glAaNTlK0vLt1jJbqhVjdGTqKFIW1uUw7dq816BVi7EzLMU8svAVbDHk2UonNDPlBzdGCqevgeQ3i');

COMMIT;
